-- messages_index.lua — GENERATED by tools/gen_messages.py. DO NOT EDIT BY HAND.
-- Edit content/*_messages.json and re-run the generator; see docs/MESSAGES.md.
--
-- Every string here is a journal `uniquePath` accepted by
--   JournalManager:ChangeEntryState(path, className, state, notifyOption)
-- The archive must contain the matching entries, which is exactly why both sides are
-- generated from one file: a beat cannot exist in Lua and be missing from the archive.

local Index = { personas = {} }

-- from content/jackie_messages.json
Index.personas["jackie"] = {
  contactPath = "contacts/jackie",
  convoPath   = "contacts/jackie/jackielives",
  beats = {
    { id = "open01", kind = "opener", tier = 0, once = true,
      bubbles = { "contacts/jackie/jackielives/open01_b1", "contacts/jackie/jackielives/open01_b2", "contacts/jackie/jackielives/open01_b3" },
      group = "contacts/jackie/jackielives/open01_g",
      replies = {
        { id = "glad", path = "contacts/jackie/jackielives/open01_g/glad", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/open01_glad_f1", "contacts/jackie/jackielives/open01_glad_f2", "contacts/jackie/jackielives/open01_glad_f3" } },
        { id = "tease", path = "contacts/jackie/jackielives/open01_g/tease", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/open01_tease_f1", "contacts/jackie/jackielives/open01_tease_f2", "contacts/jackie/jackielives/open01_tease_f3" } },
        { id = "quiet", path = "contacts/jackie/jackielives/open01_g/quiet", fam = -1, accept = false, followup = { "contacts/jackie/jackielives/open01_quiet_f1", "contacts/jackie/jackielives/open01_quiet_f2" } },
      },
    },
    { id = "chk01", kind = "checkin", tier = 0,
      bubbles = { "contacts/jackie/jackielives/chk01_b1" },
      group = "contacts/jackie/jackielives/chk01_g",
      replies = {
        { id = "fine", path = "contacts/jackie/jackielives/chk01_g/fine", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/chk01_fine_f1" } },
        { id = "rough", path = "contacts/jackie/jackielives/chk01_g/rough", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/chk01_rough_f1" } },
      },
    },
    { id = "chk02", kind = "checkin", tier = 1,
      bubbles = { "contacts/jackie/jackielives/chk02_b1", "contacts/jackie/jackielives/chk02_b2" },
      group = "contacts/jackie/jackielives/chk02_g",
      replies = {
        { id = "coming", path = "contacts/jackie/jackielives/chk02_g/coming", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/chk02_coming_f1", "contacts/jackie/jackielives/chk02_coming_f2" } },
        { id = "later", path = "contacts/jackie/jackielives/chk02_g/later", fam = 0, accept = false, followup = { "contacts/jackie/jackielives/chk02_later_f1", "contacts/jackie/jackielives/chk02_later_f2" } },
      },
    },
    { id = "chk03", kind = "checkin", tier = 2,
      bubbles = { "contacts/jackie/jackielives/chk03_b1", "contacts/jackie/jackielives/chk03_b2", "contacts/jackie/jackielives/chk03_b3" },
      group = "contacts/jackie/jackielives/chk03_g",
      replies = {
        { id = "same", path = "contacts/jackie/jackielives/chk03_g/same", fam = 2, accept = false, followup = { "contacts/jackie/jackielives/chk03_same_f1", "contacts/jackie/jackielives/chk03_same_f2", "contacts/jackie/jackielives/chk03_same_f3" } },
        { id = "here", path = "contacts/jackie/jackielives/chk03_g/here", fam = 2, accept = false, followup = { "contacts/jackie/jackielives/chk03_here_f1", "contacts/jackie/jackielives/chk03_here_f2", "contacts/jackie/jackielives/chk03_here_f3" } },
        { id = "drop", path = "contacts/jackie/jackielives/chk03_g/drop", fam = 0, accept = false, followup = { "contacts/jackie/jackielives/chk03_drop_f1", "contacts/jackie/jackielives/chk03_drop_f2" } },
      },
    },
    { id = "q01", kind = "question", tier = 1,
      bubbles = { "contacts/jackie/jackielives/q01_b1", "contacts/jackie/jackielives/q01_b2" },
      group = "contacts/jackie/jackielives/q01_g",
      replies = {
        { id = "you", path = "contacts/jackie/jackielives/q01_g/you", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/q01_you_f1", "contacts/jackie/jackielives/q01_you_f2" } },
        { id = "city", path = "contacts/jackie/jackielives/q01_g/city", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/q01_city_f1", "contacts/jackie/jackielives/q01_city_f2" } },
      },
    },
    { id = "inv_noodle", kind = "invite", tier = 2, venue = "noodle",
      bubbles = { "contacts/jackie/jackielives/inv_noodle_b1", "contacts/jackie/jackielives/inv_noodle_b2" },
      group = "contacts/jackie/jackielives/inv_noodle_g",
      replies = {
        { id = "yes", path = "contacts/jackie/jackielives/inv_noodle_g/yes", fam = 1, accept = true, followup = { "contacts/jackie/jackielives/inv_noodle_yes_f1" } },
        { id = "no", path = "contacts/jackie/jackielives/inv_noodle_g/no", fam = 0, accept = false, followup = { "contacts/jackie/jackielives/inv_noodle_no_f1" } },
      },
    },
    { id = "inv_coyote", kind = "invite", tier = 2, venue = "coyote",
      bubbles = { "contacts/jackie/jackielives/inv_coyote_b1", "contacts/jackie/jackielives/inv_coyote_b2" },
      group = "contacts/jackie/jackielives/inv_coyote_g",
      replies = {
        { id = "yes", path = "contacts/jackie/jackielives/inv_coyote_g/yes", fam = 1, accept = true, followup = { "contacts/jackie/jackielives/inv_coyote_yes_f1" } },
        { id = "no", path = "contacts/jackie/jackielives/inv_coyote_g/no", fam = 0, accept = false, followup = { "contacts/jackie/jackielives/inv_coyote_no_f1" } },
      },
    },
    { id = "su01", kind = "standup", tier = 0,
      bubbles = { "contacts/jackie/jackielives/su01_b1", "contacts/jackie/jackielives/su01_b2", "contacts/jackie/jackielives/su01_b3" },
      group = "contacts/jackie/jackielives/su01_g",
      replies = {
        { id = "sorry", path = "contacts/jackie/jackielives/su01_g/sorry", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/su01_sorry_f1" } },
        { id = "nothing", path = "contacts/jackie/jackielives/su01_g/nothing", fam = -1, accept = false, followup = { "contacts/jackie/jackielives/su01_nothing_f1" } },
      },
    },
    { id = "aft01", kind = "afterdate", tier = 1,
      bubbles = { "contacts/jackie/jackielives/aft01_b1", "contacts/jackie/jackielives/aft01_b2" },
      group = "contacts/jackie/jackielives/aft01_g",
      replies = {
        { id = "again", path = "contacts/jackie/jackielives/aft01_g/again", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/aft01_again_f1", "contacts/jackie/jackielives/aft01_again_f2" } },
        { id = "warm", path = "contacts/jackie/jackielives/aft01_g/warm", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/aft01_warm_f1", "contacts/jackie/jackielives/aft01_warm_f2", "contacts/jackie/jackielives/aft01_warm_f3" } },
      },
    },
    { id = "out01", kind = "outgoing", tier = 0,
      bubbles = {  },
      group = "contacts/jackie/jackielives/out01_g",
      replies = {
        { id = "around", path = "contacts/jackie/jackielives/out01_g/around", fam = 0, accept = false, followup = { "contacts/jackie/jackielives/out01_around_f1", "contacts/jackie/jackielives/out01_around_f2" } },
        { id = "check", path = "contacts/jackie/jackielives/out01_g/check", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/out01_check_f1", "contacts/jackie/jackielives/out01_check_f2", "contacts/jackie/jackielives/out01_check_f3" } },
        { id = "miss", path = "contacts/jackie/jackielives/out01_g/miss", fam = 2, accept = false, followup = { "contacts/jackie/jackielives/out01_miss_f1", "contacts/jackie/jackielives/out01_miss_f2", "contacts/jackie/jackielives/out01_miss_f3" } },
      },
    },
    { id = "out02", kind = "outgoing", tier = 0,
      bubbles = {  },
      group = "contacts/jackie/jackielives/out02_g",
      replies = {
        { id = "food", path = "contacts/jackie/jackielives/out02_g/food", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/out02_food_f1", "contacts/jackie/jackielives/out02_food_f2" } },
        { id = "gig", path = "contacts/jackie/jackielives/out02_g/gig", fam = 0, accept = false, followup = { "contacts/jackie/jackielives/out02_gig_f1", "contacts/jackie/jackielives/out02_gig_f2" } },
        { id = "night", path = "contacts/jackie/jackielives/out02_g/night", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/out02_night_f1", "contacts/jackie/jackielives/out02_night_f2" } },
      },
    },
    { id = "out03", kind = "outgoing", tier = 0,
      bubbles = {  },
      group = "contacts/jackie/jackielives/out03_g",
      replies = {
        { id = "misty", path = "contacts/jackie/jackielives/out03_g/misty", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/out03_misty_f1", "contacts/jackie/jackielives/out03_misty_f2" } },
        { id = "mama", path = "contacts/jackie/jackielives/out03_g/mama", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/out03_mama_f1", "contacts/jackie/jackielives/out03_mama_f2" } },
        { id = "truth", path = "contacts/jackie/jackielives/out03_g/truth", fam = 2, accept = false, followup = { "contacts/jackie/jackielives/out03_truth_f1", "contacts/jackie/jackielives/out03_truth_f2", "contacts/jackie/jackielives/out03_truth_f3" } },
      },
    },
    { id = "arc_p1_night", kind = "story", tier = 0, once = true,
      bubbles = { "contacts/jackie/jackielives/arc_p1_night_b1", "contacts/jackie/jackielives/arc_p1_night_b2", "contacts/jackie/jackielives/arc_p1_night_b3", "contacts/jackie/jackielives/arc_p1_night_b4", "contacts/jackie/jackielives/arc_p1_night_b5" },
      group = "contacts/jackie/jackielives/arc_p1_night_g",
      replies = {
        { id = "worried", path = "contacts/jackie/jackielives/arc_p1_night_g/worried", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/arc_p1_night_worried_f1", "contacts/jackie/jackielives/arc_p1_night_worried_f2" } },
        { id = "vik", path = "contacts/jackie/jackielives/arc_p1_night_g/vik", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/arc_p1_night_vik_f1", "contacts/jackie/jackielives/arc_p1_night_vik_f2" } },
        { id = "respect", path = "contacts/jackie/jackielives/arc_p1_night_g/respect", fam = 1, accept = false, followup = { "contacts/jackie/jackielives/arc_p1_night_respect_f1", "contacts/jackie/jackielives/arc_p1_night_respect_f2", "contacts/jackie/jackielives/arc_p1_night_respect_f3" } },
      },
    },
    { id = "arc_p3_blackout", kind = "story", tier = 0, once = true,
      bubbles = { "contacts/jackie/jackielives/arc_p3_blackout_b1", "contacts/jackie/jackielives/arc_p3_blackout_b2" },
    },
    { id = "arc_p3_ask", kind = "story", tier = 0, once = true,
      bubbles = { "contacts/jackie/jackielives/arc_p3_ask_b1", "contacts/jackie/jackielives/arc_p3_ask_b2", "contacts/jackie/jackielives/arc_p3_ask_b3", "contacts/jackie/jackielives/arc_p3_ask_b4", "contacts/jackie/jackielives/arc_p3_ask_b5", "contacts/jackie/jackielives/arc_p3_ask_b6", "contacts/jackie/jackielives/arc_p3_ask_b7" },
      group = "contacts/jackie/jackielives/arc_p3_ask_g",
      replies = {
        { id = "accept", path = "contacts/jackie/jackielives/arc_p3_ask_g/accept", fam = 0, accept = false, followup = { "contacts/jackie/jackielives/arc_p3_ask_accept_f1" } },
        { id = "refuse", path = "contacts/jackie/jackielives/arc_p3_ask_g/refuse", fam = 0, accept = false, followup = { "contacts/jackie/jackielives/arc_p3_ask_refuse_f1", "contacts/jackie/jackielives/arc_p3_ask_refuse_f2", "contacts/jackie/jackielives/arc_p3_ask_refuse_f3" } },
      },
    },
    { id = "arc_p5_flare", kind = "story", tier = 0,
      bubbles = { "contacts/jackie/jackielives/arc_p5_flare_b1", "contacts/jackie/jackielives/arc_p5_flare_b2", "contacts/jackie/jackielives/arc_p5_flare_b3" },
    },
  },
}

-- from content/nix_messages.json
Index.personas["jackielives_nix"] = {
  contactPath = "contacts/jackielives_nix",
  convoPath   = "contacts/jackielives_nix/thread",
  beats = {
    { id = "arc_p2_nix", kind = "story", tier = 0, once = true,
      bubbles = { "contacts/jackielives_nix/thread/arc_p2_nix_b1", "contacts/jackielives_nix/thread/arc_p2_nix_b2", "contacts/jackielives_nix/thread/arc_p2_nix_b3" },
      group = "contacts/jackielives_nix/thread/arc_p2_nix_g",
      replies = {
        { id = "pay", path = "contacts/jackielives_nix/thread/arc_p2_nix_g/pay", fam = 0, accept = false, cost = 2000, followup = { "contacts/jackielives_nix/thread/arc_p2_nix_pay_f1" } },
        { id = "haggle", path = "contacts/jackielives_nix/thread/arc_p2_nix_g/haggle", fam = 0, accept = false, followup = { "contacts/jackielives_nix/thread/arc_p2_nix_haggle_f1", "contacts/jackielives_nix/thread/arc_p2_nix_haggle_f2" } },
      },
    },
  },
}

-- from content/unknown_messages.json
Index.personas["jackielives_unknown"] = {
  contactPath = "contacts/jackielives_unknown",
  convoPath   = "contacts/jackielives_unknown/thread",
  beats = {
    { id = "arc_p2_unknown", kind = "story", tier = 0, once = true,
      bubbles = { "contacts/jackielives_unknown/thread/arc_p2_unknown_b1", "contacts/jackielives_unknown/thread/arc_p2_unknown_b2" },
      group = "contacts/jackielives_unknown/thread/arc_p2_unknown_g",
      replies = {
        { id = "who", path = "contacts/jackielives_unknown/thread/arc_p2_unknown_g/who", fam = 0, accept = false, followup = { "contacts/jackielives_unknown/thread/arc_p2_unknown_who_f1" } },
        { id = "nothing", path = "contacts/jackielives_unknown/thread/arc_p2_unknown_g/nothing", fam = 0, accept = false, followup = {  } },
      },
    },
  },
}

return Index
