--[[
  vo.lua — JACKIE'S REAL VOICE, WITHOUT SHIPPING A SINGLE AUDIO FILE  (v1.66)
  ============================================================================
  Global `VO`. Dependency-injected like familiarity.lua / retrieval.lua, so an
  unbound helper no-ops instead of erroring, and the whole file is testable on
  the Mac with no game running (tools/test_vo.lua).

  WHAT CHANGED, AND WHY IT MATTERS
  For a year this mod believed the game could not be told to play one CHOSEN
  voice line. That belief cost us Audioware, a 940 MB extraction every player
  had to perform by hand, a WolvenKit tutorial, and a failure mode where one
  missing .wav silenced Jackie completely. It was wrong. The game will play any
  line you name — you ask the DIALOGUE system, not the audio system:

      DialogLineEvent{ data = audioDialogLineEventData{ stringId = <CRUID> } }

  queued on the entity that should speak. The audio is already on the player's
  disk, because it is the game's own. See docs/research/native_vo_dialogline.md
  and reds/JackieLivesVO.reds.

  NO CONTENT CHANGES. Our voiced lines are already written as
      sfx = "jl_1660220866564214792"
  and those digits ARE the line's String ID (the trailing hex of its .wem stem,
  in decimal — verified against the game's own screenplay data, where
  screenplayStore.lines[].locstringId.ruid is exactly this number). So every
  line already in the trees routes to the native path with nothing rewritten.

  ⚠️ THE ONE THING THAT MUST NOT DRIFT: a String ID is ~2e18, and Lua numbers
  are doubles — they cannot hold it exactly above 2^53. Never `tonumber()` an
  id, never do arithmetic on one, never round-trip it through a number. It is a
  STRING here and a string all the way into redscript, which parses it with
  StringToUint64. test_vo.lua asserts this and will fail if anyone "tidies" it.

  BACKENDS, in the order VO.play tries them:
    1. native     — the shim above. Nothing to install, nothing to extract.
    2. audioware  — the old path, kept working for anyone who already built a
                    bank. Never required; if Audioware is absent it is skipped.
    3. ono grunt  — a real WWise vocal-effort event on Jackie's own body. Works
                    with NO dependency at all, which is why the "unvoiced line"
                    fallback is no longer silence-or-Audioware.
--]]

local M = {}

M.VERSION = "1.66"

-- Durations, in seconds, read out of the game's own .scene files by
-- tools/gen_vo_durations.py. Optional: a missing table or a missing entry just
-- means we pace by reading time instead.
local DUR = nil
pcall(function() DUR = require("vo_durations") end)

-- realStringId -> a SYNTHETIC id whose voiceover-map row points at the FEMALE .wem, generated by
-- tools/gen_vomap.py and merged into the game's map by ArchiveXL. This is the ONLY way to choose a
-- gendered take: a line's two takes share one String ID and the ENGINE picks the column natively —
-- nothing on `audioDialogLineEventData` or `AudioSystem` can express which one we want. The whole
-- investigation is ../NCLives/docs/research/vo_gender.md; confirmed working in game 2026-08-15.
--
-- Covers BOTH halves of the bug: V's own 41 lines, and the 6 Jackie lines CDPR recorded twice
-- because they ADDRESS V ("chica"/"mano"). Same question, so the same table.
--
-- ⚠️ These ids exist ONLY in JackieLives.archive. Speaking one without it is SILENCE, which is worse
-- than the male take — so M.femaleTakeId() refuses to hand one out until deps.archiveOk() has
-- confirmed the merge. Never bypass that check.
local FEM = nil
pcall(function() FEM = require("vo_female_ids") end)

-- ---------------------------------------------------------------------------
-- Injected from init.lua (VO.bind{...}). All optional.
-- ---------------------------------------------------------------------------
--   log(msg)                    -> console + log file
--   config() -> table           -> the LIVE Config.voice (re-read every call, because
--                                  config.lua is re-required from disk on every reload)
--   readingSecs(text) -> number -> how long that text takes to read
--   playEvent(target, event)    -> fire a WWise event on an entity (the ono grunts)
local deps = {}

function M.bind(t)
  for _, k in ipairs({ "log", "config", "readingSecs", "playEvent",
                       "bodyMale", "archiveOk", "takePref" }) do
    if t and t[k] ~= nil then deps[k] = t[k] end
  end
  return M
end

local function log(msg)
  if deps.log then pcall(deps.log, "[VO] " .. tostring(msg)) end
end

local function cfg()
  local c
  if deps.config then pcall(function() c = deps.config() end) end
  return c or {}
end

-- ---------------------------------------------------------------------------
-- Backend detection. Probed lazily, then cached — but ONLY after a positive
-- result. A negative is never cached: the shim answers through an entity, and
-- at the moment the first line is spoken there may not be a usable one yet.
-- Caching "no" there would have permanently disabled voice on a slow load.
-- ---------------------------------------------------------------------------
local state = { native = nil, audioware = nil, logged = false, version = nil }

-- Any GameObject will do — the shim is added to GameObject itself. Prefer the
-- player because it always exists.
local function probeTarget(target)
  if target then return target end
  local p
  pcall(function() p = Game.GetPlayer() end)
  return p
end

function M.hasNative(target)
  if state.native then return true end
  local t = probeTarget(target)
  if not t then return false end
  local ver
  pcall(function() ver = t:JLVO_Version() end)
  if type(ver) == "number" and ver >= 1 then
    state.native  = true
    state.version = ver
    return true
  end
  return false
end

-- ---------------------------------------------------------------------------
-- Speak ONE line through an explicit set of knobs, ignoring Config. This is the
-- A/B rig behind the CET window's "Voice lab": the event carries no position
-- field, so when a line comes out of the wrong place in the world the only
-- variables are which ENTITY it was queued on and which context/expression it
-- carried. Guessing across those from a Mac is hopeless; hearing four variants
-- back to back settles it in a minute.
-- Returns ok, plus the name of the entity that actually received it.
-- ---------------------------------------------------------------------------
function M.probe(id, target, ctx, expr, tag)
  local speaker = probeTarget(target)
  if not speaker then return false, "no entity" end
  if not M.hasNative(speaker) then return false, "shim not loaded" end

  local who = "?"
  pcall(function()
    local rec = speaker:GetRecordID()
    who = tostring(rec and rec.value or rec)
  end)
  pcall(function()
    if speaker == Game.GetPlayer() then who = who .. " (V — THE PLAYER)" end
  end)

  local ok, played = pcall(function()
    if state.version and state.version >= 2 then
      return speaker:JLVO_Speak(id, ctx or -1, expr or -1,
                                CName.new(tag or ""), CName.new("v"), 3.0)
    end
    return speaker:JLVO_PlayLine(id, ctx or -1)
  end)
  log(("probe: id=%s ctx=%s expr=%s tag=%s -> entity %s  ok=%s")
      :format(tostring(id), tostring(ctx), tostring(expr), tostring(tag or ""), who, tostring(ok and played)))
  return (ok and played) or false, who
end

function M.hasAudioware()
  if state.audioware ~= nil then return state.audioware end
  local d
  pcall(function() d = Game.GetAudioSystemExt():Duration(CName.new("jl_fallback")) end)
  state.audioware = (type(d) == "number" and d > 0)
  return state.audioware
end

-- "native" | "audioware" | "grunt" — what a voiced line would actually use now.
function M.backend(target)
  local mode = cfg().mode or "auto"
  if mode == "off" then return "off" end
  if mode ~= "audioware" and M.hasNative(target) then return "native" end
  if mode ~= "native" and M.hasAudioware() then return "audioware" end
  return "grunt"
end

-- Said once, on the first line, so the log names the backend without spamming.
local function logBackendOnce(target)
  if state.logged then return end
  state.logged = true
  local b = M.backend(target)
  if b == "native" then
    log("using the game's OWN voice-over (JackieLivesVO.reds present) — no audio files needed.")
  elseif b == "audioware" then
    log("using the Audioware bank. The native path is unavailable: r6/scripts/JackieLives/"
        .. "JackieLivesVO.reds is missing or redscript isn't installed.")
  elseif b == "off" then
    log("voice disabled by Config.voice.mode.")
  else
    log("no voice backend — Jackie will use vocal efforts + subtitles. Install redscript and "
        .. "make sure r6/scripts/JackieLives/JackieLivesVO.reds shipped with the mod.")
  end
end

-- ---------------------------------------------------------------------------
-- The id in `sfx`. Our content writes "jl_<decimal string id>"; anything else
-- (jl_fallback, test_tone, a wem-stem alias) is not a line id and belongs to
-- the Audioware path. Returned as a STRING — see the warning in the header.
-- ---------------------------------------------------------------------------
function M.lineId(sfx)
  if type(sfx) ~= "string" then return nil end
  return sfx:match("^jl_(%d%d%d%d%d%d+)$")
end

-- ---------------------------------------------------------------------------
-- The id to actually SPEAK for `id`, given who V is. nil means "speak the real id", i.e. exactly
-- what the mod did before this existed. Returns our synthetic id only when ALL of:
--   1. the player's preference allows it (deps.takePref(): auto follows V's body),
--   2. this line is genuinely gendered (it is in FEM at all), and
--   3. JackieLives.archive is merged, so the synthetic id resolves to a recording.
--
-- (3) is not paranoia. A synthetic id the game has never heard of is SILENT, and the redscript shim
-- returns true for any id it can parse — so the failure would leave no trace anywhere. Fail back.
-- ---------------------------------------------------------------------------
function M.femaleTakeId(id)
  if not (id and FEM and FEM[id]) then return nil end
  if not (deps.bodyMale and deps.archiveOk and deps.takePref) then return nil end

  -- ⚠️ The Esc-menu setting FINALLY DOES SOMETHING (v1.71). It used to pick between event SHAPES
  -- (isPlayer / voice-tag combinations) and hope; the engine cannot hear a shape, and all three were
  -- confirmed male in game. It now picks the TAKE.
  --   auto   (default) follow V's body — the same question the engine asks
  --   female force the female take, for a V whose creator VOICE differs from their BODY
  --   male   never substitute; vanilla behaviour
  -- Read through a DEP, not through Config: config.lua is re-required from disk on every reload, so
  -- a preference parked in Config.voice would evaporate and silently revert the player to Auto —
  -- the config-reload-wipes-tuning trap this repo has been bitten by before. JL.vVoice is persisted.
  local pref = "auto"
  pcall(function() pref = deps.takePref() or "auto" end)
  if pref == "male" then return nil end
  if pref ~= "female" then
    local male = true
    pcall(function() male = deps.bodyMale() end)
    if male ~= false then return nil end
  end

  local archived = false
  pcall(function() archived = deps.archiveOk() end)
  if archived ~= true then return nil end
  return FEM[id]
end

-- ---------------------------------------------------------------------------
-- How long this line lasts, in seconds. Exact where the game told us, reading
-- time otherwise, nil if we have neither and the caller should use its own
-- default.
-- ---------------------------------------------------------------------------
function M.duration(sfx, text)
  local id = M.lineId(sfx)
  if id and DUR and DUR[id] then return DUR[id] end

  -- Audioware, when it's the backend, knows its own clip lengths.
  if sfx and sfx ~= "" and state.audioware then
    local d
    pcall(function() d = Game.GetAudioSystemExt():Duration(CName.new(sfx)) end)
    if type(d) == "number" and d > 0 then return d end
  end

  if text and text ~= "" and deps.readingSecs then
    local secs
    pcall(function() secs = deps.readingSecs(text) end)
    if type(secs) == "number" and secs > 0 then return secs end
  end
  return nil
end

-- ---------------------------------------------------------------------------
-- Speak one line.
--   sfx    "jl_<id>" (native), or any Audioware event name
--   target the entity that should speak — Jackie. Falls back to the player,
--          which is what the phone-call beats need (he isn't in the world yet).
--   mute   caller says an unvoiced line should be GENUINELY silent (v1.56's
--          muteFallback): no grunt.
-- Returns true if something was actually heard.
-- ---------------------------------------------------------------------------
function M.play(sfx, target, mute)
  local c = cfg()
  if c.mode == "off" then return false end
  logBackendOnce(target)

  local id = M.lineId(sfx)
  -- The id we SPEAK may differ from the id everything else is keyed by. Durations, subtitles and
  -- logs stay on the real one; only the DialogLineEvent gets the female-take id.
  local speakId = (id and M.femaleTakeId(id)) or id
  if id and c.mode ~= "audioware" then
    local speaker = probeTarget(target)
    if speaker and M.hasNative(speaker) then
      -- ⚠️ WHICH ENTITY THIS IS QUEUED ON IS THE WHOLE BALL GAME. The event carries no
      -- position field (verified against the RTTI dump: stringId, context, expression,
      -- isPlayer, isRewind, isHolocall, customVoEvent, seekTime, playbackSpeedParameter —
      -- and nothing else), so the ONLY thing that can place the voice in the world is the
      -- entity it is queued on. Queue it on the player and Jackie's voice comes out of V.
      -- That is why `target` is threaded through every caller rather than defaulted.
      local ok, played = pcall(function()
        local tag  = c.voiceTag or ""
        local rest = c.restoreVoiceTag or ""
        if state.version and state.version >= 2 then
          return speaker:JLVO_Speak(speakId, c.context or -1, c.expression or -1,
                                    CName.new(tag), CName.new(rest), M.duration(sfx) or 3.0)
        end
        -- a stale .reds next to a new .lua: still speak, just without `expression`
        if tag ~= "" then
          return speaker:JLVO_PlayLineAs(speakId, c.context or -1, CName.new(tag),
                                         CName.new(rest), M.duration(sfx) or 3.0)
        end
        return speaker:JLVO_PlayLine(speakId, c.context or -1)
      end)
      if ok and played then return true end
      -- A well-formed id the game doesn't know is silent, not an error, so this
      -- only trips on a genuinely malformed id — worth saying out loud.
      log("native playback refused id " .. tostring(id) .. " (ok=" .. tostring(ok) .. ")")
    end
  end

  if sfx and sfx ~= "" and c.mode ~= "native" and M.hasAudioware() then
    local ok = pcall(function() Game.GetAudioSystemExt():Play(CName.new(sfx)) end)
    if ok then return true end
  end

  -- Nothing voiced. A vocal effort keeps him from reading as broken, and unlike
  -- everything above it needs no dependency whatsoever — these are WWise events
  -- that ship with the game and play on his own body.
  --
  -- ⚠️ v1.69 — RARE, NOT EVERY LINE. Most of the hub small talk is written text (there is no
  -- CDPR recording of "how's Mama Welles"), so before this the grunt fired on EVERY unvoiced
  -- line: pick a topic, hear a grunt; go back, hear a grunt. It stopped reading as "he made a
  -- sound" and started reading as "the mod is broken". `gruntChance` makes it an occasional
  -- punctuation instead — the effect Antonia liked, at the frequency that keeps it likeable.
  -- 1.0 restores the old always-grunt behaviour; 0 disables it without touching gruntPool.
  if mute then return false end
  local chance = c.gruntChance
  if chance == nil then chance = 0.15 end
  if chance < 1.0 then
    local r = 1.0
    pcall(function() r = math.random() end)
    if r >= chance then return false end
  end
  local pool = c.gruntPool
  if pool and #pool > 0 and deps.playEvent and target then
    local ev = pool[math.random(1, #pool)]
    local ok = pcall(function() deps.playEvent(target, ev) end)
    -- ⚠️ v1.69.1 SAY IT OUT LOUD, EVERY TIME. "He still grunts on every selection" was impossible to
    -- act on because a grunt leaves no trace: three different conditions land here and the log
    -- couldn't tell them apart. Now one line names the cause, so the next report is one grep:
    --   sfx=nil            -> the line was never given a clip. Look it up (see the SMALL TALK note
    --                         in config.lua) — since v1.66 "we have no recording" is almost never true.
    --   sfx=jl_... native  -> the id is real but the native path refused it or isn't installed. If
    --                         `backend` says grunt, redscript/JackieLivesVO.reds is the problem and
    --                         EVERY line is grunting, which is the "every time" symptom.
    -- `chance` is echoed so a stale deploy is obvious: if it says 1.00, the running config.lua
    -- predates the fix no matter what the repo says.
    if ok then
      log(("vocal effort '%s' — sfx=%s backend=%s chance=%.2f")
          :format(tostring(ev), tostring(sfx), M.backend(target), chance))
      return true
    end
  end
  return false
end

-- ---------------------------------------------------------------------------
-- Drop every cached probe and re-arm the "which backend am I on" log line.
--
-- Called when the player switches backend in the CET window. Without this, two
-- things would go stale in a way that reads as a bug: `logged` means the log
-- never names the NEW backend, and a cached positive `native` means "Audioware
-- only" would still look like it had a native path available. Cheap to call —
-- the probes are one method call each.
-- ---------------------------------------------------------------------------
function M.forget()
  state.native, state.audioware, state.logged, state.version = nil, nil, false, nil
end

-- ---------------------------------------------------------------------------
-- One-line health report for the CET window / Diagnostics.
-- ---------------------------------------------------------------------------
function M.status(target)
  local b = M.backend(target)
  local n = 0
  if DUR then for _ in pairs(DUR) do n = n + 1 end end
  -- v1.69.1: gruntChance is in here because "he still grunts every time" is far more often a stale
  -- deploy than a bug — the .lua files are copied by hand to the game folder, so the repo being
  -- right says nothing about what's running. If this reads 1.00, the game is on an old config.lua.
  local gc = cfg().gruntChance
  return "backend=" .. b
      .. " native=" .. tostring(M.hasNative(target))
      .. " audioware=" .. tostring(M.hasAudioware())
      .. " shim=v" .. tostring(state.version or "?")
      .. " durations=" .. tostring(n)
      .. " gruntChance=" .. string.format("%.2f", gc == nil and 0.15 or gc)
end

return M
