-- GENERATED by tools/gen_vo_gender.py — DO NOT HAND-EDIT.
--
-- Some Jackie lines were recorded TWICE under ONE String ID: once addressed to a female V
-- ("chica"), once to a male V ("mano"). The game picks the take from V's BODY GENDER all by
-- itself — we never chose it and we cannot change it. What we DO control is the subtitle, and
-- config.lua's text was written from the female take, so a male-V player heard "mano" and read
-- "chica". That is the bug this table closes: same line id, subtitle picked to match.
--
-- ⚠️ This is V's BODY GENDER, not the mod's Husbando/Hermano switch. The switch is a
-- RELATIONSHIP track and it is the player's to choose; which take the audio engine reaches for
-- is decided by the save file. Mixing the two is exactly how we got here.
--
-- Text is CDPR's own, exactly as the game would render it (the <mothertongue>/<kiroshi> splice
-- markup resolved), so the subtitle matches the audio word for word.
--
--   ["<string id>"] = { f = "<female-V subtitle>", m = "<male-V subtitle>" }

return {
  ["1155727714874494976"] = { f = "Time we were on our way, mamita.",
                               m = "Time we were on our way, carnal." },
  ["1661700260668284928"] = { f = "Don't come here often, do ya? Heheh. It's good to see you, chica.",
                               m = "Don't come here often, do ya? Heheh. It's good to see you, cabrón." },
  ["1777946122915868672"] = { f = "Straight to biz, eh, chica?",
                               m = "Straight to biz, eh, mano?" },
  ["1966199076127907844"] = { f = "You with me, chica?",
                               m = "You with me, mano?" },
  ["2008322358689853440"] = { f = "Chica! Finally!",
                               m = "Hermano! Finally!" },
  ["2238739839238447112"] = { f = "Make moves, chica.",
                               m = "Make moves, mano." },
}
