#!/usr/bin/env python3
"""
Convert Jackie's scraped voice lines (Opus-in-Ogg, which Audioware CANNOT decode)
into Ogg Vorbis (which it can), and (re)generate the Audioware manifest.

Source : tools/voice-tagger/audio/<string_id>.ogg   (Opus)
Output : audioware/JackieLives/jl_<string_id>.ogg     (Vorbis)
Manifest: audioware/JackieLives/JackieLives.yml        (all lines + test_tone + jl_fallback)
Index   : audioware/JackieLives/index.json             (string_id -> {event, text})

Uses the portable ffmpeg in tools/ffmpeg (no system install). Idempotent: skips
files already converted unless --force.
"""
import json, subprocess, sys, os, glob, argparse

ROOT   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # project root
AUDIO  = os.path.join(ROOT, "tools", "voice-tagger", "audio")
LINES  = os.path.join(ROOT, "tools", "voice-tagger", "lines.json")
BANK   = os.path.join(ROOT, "audioware", "JackieLives")

def find_ffmpeg():
    hits = glob.glob(os.path.join(ROOT, "tools", "ffmpeg", "**", "ffmpeg.exe"), recursive=True)
    if hits:
        return hits[0]
    # fall back to PATH
    return "ffmpeg"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="reconvert even if output exists")
    ap.add_argument("--limit", type=int, default=0, help="convert only the first N (debug)")
    args = ap.parse_args()

    ffmpeg = find_ffmpeg()
    print(f"ffmpeg: {ffmpeg}")
    os.makedirs(BANK, exist_ok=True)

    with open(LINES, encoding="utf-8") as f:
        lines = json.load(f)
    if args.limit:
        lines = lines[:args.limit]

    ok, skip, fail = 0, 0, 0
    index = {}
    manifest_entries = []   # (event, filename)

    for e in lines:
        sid = e["id"]
        src = os.path.join(AUDIO, f"{sid}.ogg")
        if not os.path.exists(src):
            fail += 1; continue
        event = f"jl_{sid}"
        out_name = f"{event}.ogg"
        dst = os.path.join(BANK, out_name)
        index[sid] = {"event": event, "text": e.get("transcript", "")}
        manifest_entries.append((event, out_name))
        if os.path.exists(dst) and not args.force:
            skip += 1; continue
        # -c:a libvorbis: re-encode Opus -> Vorbis; -q:a 4 ~ 128kbps VBR (small, clean)
        cmd = [ffmpeg, "-y", "-loglevel", "error", "-i", src,
               "-c:a", "libvorbis", "-q:a", "4", dst]
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode == 0 and os.path.exists(dst):
            ok += 1
        else:
            fail += 1
            print(f"  FAIL {sid}: {r.stderr.strip()[:160]}")
        if (ok + skip) % 100 == 0:
            print(f"  ... {ok} converted, {skip} skipped")

    print(f"DONE: {ok} converted, {skip} skipped, {fail} failed/missing. {len(manifest_entries)} lines in manifest.")

    # --- write manifest ----------------------------------------------------
    yml = []
    yml.append("# Jackie Lives - Audioware sound bank (auto-generated by tools/convert_audio.py)")
    yml.append("# Play from CET Lua:  Game.GetAudioSystemExt():Play(CName.new(\"jl_<string_id>\"))")
    yml.append("# Lines are Jackie's real voice (website .ogg, re-encoded Opus->Vorbis).")
    yml.append("# FUTURE: replace with full-quality game .wem (extract via WolvenKit; vo_wem in lines.json).")
    yml.append("version: 1.0.0")
    yml.append("sfx:")
    # always-present test + fallback (shipped WAVs, not in lines.json)
    yml.append("  test_tone:")
    yml.append("    file: test_tone.wav")
    yml.append("    settings:")
    yml.append("      volume: 1.0")
    yml.append("  jl_fallback:")
    yml.append("    file: jl_fallback.wav")
    yml.append("    settings:")
    yml.append("      volume: 1.0")
    for event, fname in manifest_entries:
        yml.append(f"  {event}:")
        yml.append(f"    file: {fname}")
    manifest_path = os.path.join(BANK, "JackieLives.yml")
    with open(manifest_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(yml) + "\n")
    print(f"wrote manifest: {manifest_path} ({len(manifest_entries)+2} entries)")

    # --- write index for the mod / for picking lines -----------------------
    with open(os.path.join(BANK, "index.json"), "w", encoding="utf-8") as f:
        json.dump(index, f, ensure_ascii=False, indent=1)
    print(f"wrote index.json ({len(index)} lines)")

if __name__ == "__main__":
    main()
