-- tools/gen_storyboard_doc.lua — render the story as a readable document.
--
--   lua tools/gen_storyboard_doc.lua > docs/QUESTLINE.md
--
-- The document is GENERATED, never hand-written, for one reason: a design doc and an
-- implementation drift apart the moment they are two files. `storyboard.lua` and `sidequests.lua`
-- are what the game actually runs, so a document rendered from them is true by construction — and
-- if a beat is missing from the doc, it is missing from the mod.
--
-- Stock Lua 5.x, no game, no dependencies.

package.path = "mod/JackieLives/?.lua;" .. package.path

local Story = require("storyboard")
local Side  = require("sidequests")

local out = {}
local function w(fmt, ...)
  out[#out + 1] = select("#", ...) > 0 and string.format(fmt, ...) or fmt
end

local function hours(win)
  if not win then return "" end
  local function fmt(h)
    h = h % 24
    return string.format("%02d:%02d", math.floor(h), math.floor((h % 1) * 60 + 0.5))
  end
  return fmt(win[1]) .. "–" .. fmt(win[2])
end

local function placeLabel(key)
  if not key or key == "any" then return "anywhere" end
  if key == "jackie_current" then return "wherever Jackie is" end
  if key == "near_jackie" then return "near Jackie" end
  local p = Story.PLACES[key]
  if not p then return key end
  return p.label .. (p.needsCapture and " *(coords not captured yet)*" or "")
end

w("<!-- GENERATED by tools/gen_storyboard_doc.lua — do not edit by hand.")
w("     The source of truth is mod/JackieLives/storyboard.lua + sidequests.lua. -->")
w("")
w("# %s — the questline", Story.arc.title)
w("")
w("_JackieLives 2.0. Generated from the shipped story data (%s)._", Story.VERSION)
w("")

-- The framing material, lifted straight out of the storyboard so it cannot drift either.
w("## The story")
w("")
w("**Dramatic question.** What did it cost to keep Jackie Welles alive — and who gets to decide")
w("whether he pays it?")
w("")
w("**Theme — salvage.** Everyone here is built out of parts meant for something else.")
w("")
w("| | Wants | Needs | Flaw | Completes when |")
w("|---|---|---|---|---|")
w("| **Jackie** | To stay out, and to be enough without a gun | To accept the man who died at Konpeki isn't coming back | \"I'm fine, mano\" | He tells V the truth before being asked |")
w("| **V** | To keep Jackie safe | To stop managing him | The reunion lie about the Relic | They hand him back the choice — or knowingly don't |")
w("")

w("## Structure")
w("")
w("| Part | Title | What it is | Rests at |")
w("|---|---|---|---|")
for _, p in ipairs(Story.arc.parts) do
  w("| %s | **%s** | %s | %s |", p.id:upper(), p.title,
    (p.logline or ""):gsub("\n", " "), (p.rest or ""):gsub("\n", " "))
end
w("")

for _, part in ipairs(Story.arc.parts) do
  w("---")
  w("")
  w("## %s — \"%s\"", part.id:upper(), part.title)
  w("")
  w("> %s", (part.logline or ""):gsub("\n", " "))
  w("")
  w("**What this part is for.** %s", (part.intent or ""):gsub("\n", " "))
  w("")
  if part.arms then
    local bits = {}
    if part.arms.stage then bits[#bits + 1] = "the retrieval questline is finished" end
    if part.arms.arc then bits[#bits + 1] = "the arc has reached stage " .. part.arms.arc end
    if part.arms.daysSinceStage then bits[#bits + 1] = part.arms.daysSinceStage .. " in-game days since the reunion" end
    if part.arms.daysSincePart then bits[#bits + 1] = part.arms.daysSincePart .. " in-game days since the previous part" end
    if part.arms.familiarity then bits[#bits + 1] = "familiarity at least " .. part.arms.familiarity end
    if #bits > 0 then w("**Opens when:** %s.", table.concat(bits, ", ")); w("") end
  end

  if part.heat then
    w("**Heat.** A hidden counter (`%s`) that rises while Jackie is out in the world with V and", part.heat.fact)
    w("never decays on its own:")
    w("")
    w("| Threshold | What happens |")
    w("|---|---|")
    for _, t in ipairs(part.heat.thresholds or {}) do
      w("| %d | `%s` |", t.at, t.event)
    end
    w("")
  end

  for _, b in ipairs(part.beats or {}) do
    w("### %s — %s", b.title or b.id, "`" .. b.id .. "`")
    w("")
    local meta = {}
    if b.kind then meta[#meta + 1] = "**" .. b.kind .. "**" end
    if b.place then meta[#meta + 1] = placeLabel(b.place) end
    if b.window then meta[#meta + 1] = hours(b.window) end
    if b.actors then meta[#meta + 1] = "with " .. table.concat(b.actors, ", ") end
    if #meta > 0 then w("%s", table.concat(meta, " · ")); w("") end

    if b.intent then w("%s", (b.intent):gsub("\n", " ")); w("") end

    if b.script then
      w("**On screen:**")
      for _, line in ipairs(b.script) do w("- %s", line) end
      w("")
    end

    if b.sms then
      w("**The texts** (thread `%s`):", b.sms.thread or "jackie")
      w("")
      for _, m in ipairs(b.sms.messages or {}) do
        w("> **%s:** %s%s", m.from, m.text, m.stampNote and ("  \n> _(" .. m.stampNote .. ")_") or "")
      end
      if b.sms.replies then
        w("")
        w("V can reply:")
        for _, r in ipairs(b.sms.replies) do
          w("- *%s*%s", r.text, r.cost and (" — costs €$" .. r.cost) or "")
          for _, f in ipairs((b.sms.followups or {})[r.id] or {}) do
            w("    - > %s", f.text)
          end
        end
      end
      w("")
    end

    if b.shard then
      w("**Shard — \"%s\"** (%s):", b.shard.title, b.shard.author or "unsigned")
      w("")
      for _, line in ipairs(b.shard.body or {}) do
        w("> %s", line == "" and "" or line)
      end
      w("")
    end

    if b.journal then
      w("**Journal objective:** %s", b.journal.text or b.journal.objective)
      w("")
    end

    if b.choices then
      w("**Choices:**")
      w("")
      for _, c in ipairs(b.choices) do
        w("- **\"%s\"**%s", c.text, c.ending and (" → ending: " .. tostring(c.endingName or c.ending)) or "")
        if c.outcome then w("  %s", (c.outcome):gsub("\n", " ")) end
        if c.computed then
          w("  Read off the save, in order:")
          for _, r in ipairs(c.computed.rules or {}) do
            if r.fallback then w("    - otherwise → ending %d", r.fallback)
            else w("    - `%s` → ending %d — %s", r.when, r.ending, (r.why or ""):gsub("\n", " ")) end
          end
        end
      end
      w("")
    end

    if b.vo then
      local slots = {}
      for k, v in pairs(b.vo) do if type(v) == "string" then slots[#slots + 1] = k .. ": " .. v end end
      table.sort(slots)
      if #slots > 0 then w("_Voice: %s_", table.concat(slots, ", ")); w("") end
    end

    if b.notes then w("_Note: %s_", (b.notes):gsub("\n", " ")); w("") end
  end
end

w("---")
w("")
w("## The side quests")
w("")
w("| Quest | Slot | Length | What it plants |")
w("|---|---|---|---|")
for _, q in ipairs(Side.quests) do
  w("| **%s** | %s | %s | %s |", q.title, q.slot, q.length or "", (q.plants or ""):gsub("\n", " "))
end
w("")

for _, q in ipairs(Side.quests) do
  w("### %s — `%s`", q.title, q.id)
  w("")
  w("> %s", q.logline or "")
  w("")
  w("%s", (q.intent or ""):gsub("\n", " "))
  w("")
  for _, b in ipairs(q.beats or {}) do
    local meta = { "**" .. (b.kind or "?") .. "**" }
    if b.place then meta[#meta + 1] = placeLabel(b.place) end
    if b.window then meta[#meta + 1] = hours(b.window) end
    w("- `%s` — %s", b.id, table.concat(meta, " · "))
    if b.intent then w("  %s", (b.intent):gsub("\n", " ")) end
    for _, c in ipairs(b.choices or {}) do
      w("    - **\"%s\"** %s", c.text, c.outcome and ("— " .. (c.outcome):gsub("\n", " ")) or "")
    end
    for _, cb in ipairs(b.callbacks or {}) do w("    - callback: %s", cb) end
  end
  w("")
end

w("---")
w("")
w("## What still needs capturing in-game")
w("")
w("%s", Story.CAPTURE_LIST.note)
w("")
w("| Place | Why | How |")
w("|---|---|---|")
for _, row in ipairs(Story.CAPTURE_LIST) do
  w("| `%s` | %s | %s |", row.place, row.why, row.how)
end
w("")

w("## Casting — what Jackie can actually say")
w("")
w("Every beat names a *casting slot*, never a recording. These are the slots and what the audit")
w("(`docs/research/arc_casting.md`) found for each.")
w("")
w("| Slot | Recordings | What it has to carry |")
w("|---|---|---|")
local slots = {}
for k in pairs(Story.CASTING) do slots[#slots + 1] = k end
table.sort(slots)
for _, k in ipairs(slots) do
  local c = Story.CASTING[k]
  w("| `%s` | %d | %s |", k, #(c.ids or {}), (c.need or ""):gsub("\n", " "))
end
w("")

print(table.concat(out, "\n"))
